name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Node 18 también funciona, pero 20 es más estable
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Eleventy site
        run: |
          npm run build
          [ -f docs/.nojekyll ] || touch docs/.nojekyll  # Asegura que .nojekyll esté en docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/" # Ruta personalizada que coincides con tu configuración

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # ¡Versión actualizada!
