name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Checkout + Setup
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # 2. Seguridad
      - name: Audit dependencies
        run: npm audit --audit-level=critical

      # 3. Instalación y Build
      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build Eleventy site
        run: |
          npm run build
          [ -f docs/.nojekyll ] || touch docs/.nojekyll

      # 4. Validación de contenido (nuevo)
      - name: Validate HTML output
        uses: chabad360/htmlproofer@main
        with:
          directory: "./docs"
          arguments: "--only-4xx --check-html" # Verifica links rotos y HTML válido

      # 5. Despliegue
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/"

      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
